#security:
#  user:
#    name: buzz
#    password: infinity
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  data:
    rest:
      base-path: /api
  kafka:
    template:
      default-topic: tacocloud.orders.topic
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
      
#logging:
#  level:
#    org.springframework.data.rest: debug

---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: scotlandyard

  config:
    activate:
      on-profile: prod
logging:
  level:
    tacos: WARN
    
